services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db 
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql


